### ISSUE TITLE
Naming and Interface

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqBayes.jl#11]
I think we should look at the naming a little bit more. `bayesian_inference` I think is a function call that can work with both Stan.jl and Turing.jl. I think we should just have some way of specifying which "backend" to use here, since they both can take in the same arguments (theoretically this is all Turing.jl needs, with maybe some more keyword args? @xukai92 ?) and both of the spit out Mamba chains so the output (and thus output handling) can even be the same.

**Comment by goedman** [comment]
When I started working on Stan.jl my objective was to make Stan.jl and Mamba (and then MCMC, now Klara, in fact) modeling results and diagnostics comparable, hence the choice to use Mamba.Chains.

This proposal represents the first step in the next big step, a "Plots.jl approach" to available MCMC backends. Of course Turing, Klara, Mamba and Stan are quite different (I don't know Turing well enough), again not unlike the Plots eco system. I almost can see a next GSoC project!

If changes are needed for this in Stan.jl I will certainly be willing to go there.

**Comment by tpapp** [comment]
@goedman, thanks for the ping. This summer I have completed an implementation of "NUTS 2.0", ie pretty much the current algorithm in [Betancourt (2017)](https://arxiv.org/abs/1701.02434). We have used it in Dorisz Albrecht's GSOC project for indirect Bayesian inference. I have to complete the documentation (docstrings are in place, but want to set up `Documenter.jl`), then I will register it.

I have other packages for Bayesian inference, but instead of a single interface, I follow a more "unix-style" approach, composing small pieces. The above for inference, [another for convergence diagnostics](https://github.com/tpapp/MCMCDiagnostics.jl), yet another for converting between [ℝⁿ and a bunch of constrained parameters](https://github.com/tpapp/ContinuousTransformations.jl), and other ones are in the works (mostly for posterior predictive checks).

The interface is a bit fluid, but fairly basic: give it a callable object which produces a log likelihood and a gradient using `DiffBase.DiffResult`, and unless you want to tweak the algorithm, this is pretty much it. That said, I am happy to support changes too. However, I am exploring indirect inference these days, which requires some extras to the interface.

**Comment by ChrisRackauckas** [comment]
What we're looking for here is an easy front-end to Bayesian engines just for estimation of differential equations though. I agree that in general Bayesian estimation tools are too varied and complex to put under one umbrella, but for this specific purpose I think we can give an interface that is "here is the differential equation and the priors, what does Bayesian estimation say?" The "what does Bayesian estimation say?" is purposely vague because I think a lot of people who look into this are more on the side of differential equation modelers and not Bayesian statisticians, so while options should be available, there needs to be a sense of "just work"s with very basic knowledge of what a prior is.

In this sense I hope to at least have a front end over Stan (since it's so popular and necessary for comparisons and benchmarking) and a native Julia implementation (since that would allow using all of DifferentialEquations.jl which is the main purpose). For the latter right now we have been looking into Turing.jl (since it seems like it would be very easy to finish this up, and we know it for sure it will work), but maybe there's other tools we should target as well. Of course, for the native Julia side since I am not much of a Bayesian statistician I am just going to have the first target be the tool that I get help implementing, and then look for others in the future.

The goal here is that people who know DiffEq and its parameterized functions can easily make the switch to "okay I have data: let's do Bayesian estimation?" and get going without having to learn something new. This will never cover everything, but I think we can at least have something that does quite well and is mostly automatic (with options available of course). `bayesian_inference` mostly does this already, but it's limited in the DiffEq sense by what Stan can do and that seems to be a pretty hard limitation.

**Comment by xukai92** [comment]
Actually Stan.jl currently has more tuneable parameters than Turing.jl so if it works for Stan.jl it works for Turing.jl. We are also working on making Turing.jl accept/adapt Stan.jl interface (https://github.com/yebai/Turing.jl/issues/326) so that we can compare the inference results easily. Once this is done I think the backend switch would be more constant (on the sampler parameter side).

**Comment by tpapp** [comment]
@ChrisRackauckas : if you can write the likelihood (posterior) as a function of the parameters, `DynamicHMC.jl` can estimate it with NUTS (MCMC). You can autodiff, or calculate the derivatives yourself.

It is a native Julia implementation. The reason I wrote it is the following: existing Julia implementations, including `Mamba`, `Klara`, `Turing`, and wrappers such as `Stan`, all require that I specify probability distributions in a DSL that describes a directed acyclic graph. If I want something else, like a non-canonical distribution, or just a likelihood that I calculate using summary statistics, this is considered "advanced" usage, and requires extra boilerplate or tricks (see [for Turing](https://github.com/yebai/Turing.jl/wiki/Advanced-usages#how-to-define-a-customized-distribution), [this discussion for Mamba](https://github.com/brian-j-smith/Mamba.jl/issues/110)).

`DynamicHMC` instead just takes a `ℝⁿ→ℝ` function which is the log density, and samples from that. The advantage is that you can be very flexible with this, and you really get to optimize this, both in terms of algorithmic tricks and plain vanilla profiling and benchmarking. The disadvantage is of course that you don't get the DSL for the DAG. But essentially, a posterior is nothing but a sum of log densities, so it is not that complicated.

Two more things that you should be aware of:

1. Stan compiles the model into C++, which is then compiled to a binary. This step is sometimes as costly as running the MCMC. @goedman's `Stan.jl` wrapper caches the compiled binary for the *same* model. If you can write general model families in Stan for various differential equations, you save a lot of time. I don't know if this is possible though; but otherwise you pay a huge up-front cost.

2. Because the log density is `ℝⁿ→ℝ`, in theory reverse autodiff would be preferable to forward AD, especially for large `n`. Stan has mostly reverse. Julia's `ReverseDiff.jl` needs some work though, so almost everyone is using `ForwardDiff.jl` ATM. This puts a performance penalty on Julia implementations, but when `ReverseDiff` catches up, it should magically speed things up (but `ForwardDiff.jl` scales surprisingly nicely).

**Comment by ChrisRackauckas** [comment]
I just have two functions, `stan_inference` and `turing_inference` which solves the Bayesian problem with the two packages. That works for now.

**Comment by goedman** [comment]
As I said before, I like the stan_inference setup. In Stan.jl I have experimented with it a bit more and have 2 observations:

1. I like to work within controlled subdirectories in order to be able to store and reuse multiple compiled models (current setup in stan_inference uses the home directory for all models).
2. Further use of DiffEqBayes will show if the current balance between string replacement in the Stan language file/string vs. passing in parameters (e.g. I used abstol & co, although that is not a strong example) is the correct one. In the latter case the Stan program does not have to be re-compiled (if item 1 above is also used).

Not sure if recompiling a Stan program adds significant time in most ODE cases.

**Comment by ChrisRackauckas** [comment]
>Further use of DiffEqBayes will show if the current balance between string replacement in the Stan language file/string vs. passing in parameters (e.g. I used abstol & co, although that is not a strong example) is the correct one. In the latter case the Stan program does not have to be re-compiled (if item 1 above is also used).

Yeah, this can always be refined later.

>Not sure if recompiling a Stan program adds significant time in most ODE cases.

I don't think it does. Our test problem is as simple of a DE estimation problem that's practical, and it runs for minutes with the compilation taking seconds. I see this taking hours "normally", so the compilation time really isn't an issue. But more things can be passed in and the compilation can be cached if this seems necessary in the future. I think the bigger deal right now is hooking into more features, like allowing more types for priors.

**Comment by skanskan** [comment]
> @ChrisRackauckas : if you can write the likelihood (posterior) as a function of the parameters, `DynamicHMC.jl` can estimate it with NUTS (MCMC). You can autodiff, or calculate the derivatives yourself.
> 
> It is a native Julia implementation. The reason I wrote it is the following: existing Julia implementations, including `Mamba`, `Klara`, `Turing`, and wrappers such as `Stan`, all require that I specify probability distributions in a DSL that describes a directed acyclic graph. If I want something else, like a non-canonical distribution, or just a likelihood that I calculate using summary statistics, this is considered "advanced" usage, and requires extra boilerplate or tricks (see [for Turing]


Which is the best one: Stan, Klara, DynamicHMC, Mamba, Lora, Turing, other…?
I mean faster and able to converge with complex models, using GPU is a plus.
Stan doesn't deal easily with discrete parameters.

Is there anything like rstanarm or brms for Julia? (automatically convert regression models specified by a simple equation to MCMC).

**Comment by ChrisRackauckas** [comment]
We don't have interfaces to Klara, Mamba, or Lora. DynamicHMC seems to be faster than Turing, but Turing can use DynamicHMC now so it doesn't matter all that much. Using the ABC method is the fastest but can introduce some error. Stan can't use most of the ODE solvers, and only can do ODEs, which is a big minus. DynamicHMC's interface isn't ready on v1.0 right now, so the `turing_inference` method is what I'd prefer out of our offerings right now.

>I mean faster and able to converge with complex models, using GPU is a plus.

The expensive part is by far the likelihood evaluation. If you GPU the ODE solve then you'd be good.

**Comment by tpapp** [comment]
> DynamicHMC's interface isn't ready on v1.0 right now

FWIW, DynamicHMC 1.0 was released a few days ago, with a new interface, working fine on 1.0. 
https://tpapp.github.io/post/dynamichmc-reorganization/

There is a repo with examples, and I am happy to support any extensions you need, or help out with formulating particular models.

**Comment by ChrisRackauckas** [comment]
@Vaibhavdixit02 will probably ask for help when updating. We want to get compatible with you again ASAP.

**Comment by ChrisRackauckas** [comment]
See #55
