### ISSUE TITLE
Add docs to juliadiffeq.org website

### ISSUE THREAD

**Issue by Ayush-iitkgp** [JuliaDiffEq/DiffEqBayes.jl#13]
Now that we have the initial version ready, the next step is to add the explicit documentation for the new package [here](http://docs.juliadiffeq.org/latest/analysis/parameter_estimation.html). I will try to take time out of my schedule and try completing it in coming days. Other feel free to help us.

**Comment by ChrisRackauckas** [comment]
It may be jumping the gun a little bit because the initial version probably cannot release until Turing.jl is v0.6-compatible. But I guess we can just release it anyways since there's nothing we can do about that, and then sooner or later it will "magically work" when Turing updates. That's probably a good idea.
