### ISSUE TITLE
Problem in code generated on using multiple priors in stan_inference

### ISSUE THREAD

**Issue by Vaibhavdixit02** [JuliaDiffEq/DiffEqBayes.jl#18]
@goedman There seems to be some problem with using multiple priors (including Truncated Normal) in `stan_inference()` the Stan model generated was as mentioned below. Can you explain what `int<lower=1> T;` is for? I can't understand its role.
Thanks!  

```
functions {
   real[] sho(real t,real[] internal_var___u,real[] theta,real[] x_r,int[] x_i) {
       real internal_var___du[2];
       # /home/vaibhav/.julia/v0.6/DiffEqBayes/test/stan.jl, line 23:;
       internal_var___du[1] = theta[1] * internal_var___u[1] - theta[2] * internal_var___u[1] * internal_var___u[2];
       # /home/vaibhav/.julia/v0.6/DiffEqBayes/test/stan.jl, line 24:;
       internal_var___du[2] = -theta[3] * internal_var___u[2] + theta[4] * internal_var___u[1] * internal_var___u[2];
       return internal_var___du;
      }
    }
  data {
      real u0[2];
      int<lower=1> T;
      real internal_var___u[T,2];
      real t0;
      real ts[T];
  }
  transformed data {
       real x_r[0];
       int x_i[0];
  }
   parameters {
       vector<lower=0>[2] sigma;
       real theta[4];
  }
  model{
       real u_hat[T,2];
       sigma ~ inv_gamma(2, 3);
       theta[1] ~ normal(1.5, 1.0);theta[2] ~ normal(1.0, 1.0) T[0.0,1.0];theta[3] ~ normal(3.0, 1.0);theta[4] ~ normal(1.0, 1.0) T[0.0,1.0];
       u_hat = integrate_ode_rk45(sho, u0, t0, ts, theta, x_r, x_i, 0.001, 1.0e-6, 100000);
       for (t in 1:T){
            internal_var___u[t] ~ normal(u_hat[t], sigma);
        }
  }  
```

**Comment by Vaibhavdixit02** [comment]
@goedman it would be very helpful if you could take a look at this. Thanks!

**Comment by goedman** [comment]
First of all, apologies for not spotting this 5 days ago. Not sure why I missed it.

Can you tell me what error messages you get? Both the first and second parts of the stan.jl in tests seem to run. I separated both parts and moved my testing to Stan.jl.

With respect to your questions, have you read sections 3.1 (Constrained types) and 12.2 of the Stan Language Reference manual ( https://github.com/stan-dev/stan/releases/download/v2.17.0/stan-reference-2.17.0.pdf )? Not sure if I can explain it better.

But I must admit, I don't understand what you are trying to do. It says "four parameter model", but the Stan model only has 2 sigma and 1 theta parameters.

<img width="972" alt="screen shot 2018-01-12 at 13 03 45" src="https://user-images.githubusercontent.com/52200/34874394-19991248-f799-11e7-9f6d-d6b248f83951.png">

<img width="829" alt="screen shot 2018-01-12 at 13 04 02" src="https://user-images.githubusercontent.com/52200/34874534-90151b10-f799-11e7-8336-fc684001e0a7.png">

[LotkaVolterra-summaryplot-1.pdf](https://github.com/JuliaDiffEq/DiffEqBayes.jl/files/1625976/LotkaVolterra-summaryplot-1.pdf)

**Comment by ChrisRackauckas** [comment]
@goedman the error shows up in our tests.

https://travis-ci.org/JuliaDiffEq/DiffEqBayes.jl/jobs/327872441#L1214

Basically, it seems like if we run the 4 parameter version right after the 1 parameter version there's a compilation problem which shows up. If they are ran separately then I believe @Vaibhavdixit02 said it works (please confirm)?

>but the Stan model only has 2 sigma and 1 theta parameters.

The model that is generated has:

```
   parameters {
       vector<lower=0>[2] sigma;
       real theta[4];
  }
```

Note that for this second case, the tests here uses two different ODE systems:

https://github.com/JuliaDiffEq/DiffEqBayes.jl/blob/master/test/stan.jl

one with a single parameter to estimate and one with 4 parameters to estimate.

**Comment by Vaibhavdixit02** [comment]
@goedman in the screenshot of your "four parameter model" you have the model.
"""
f1 = @ode_def_nohes LotkaVolterraTest1 begin
  dx = a*x - b*x*y
  dy = -c*y + d*x*y
end a=>1.5 b=1.0 c=3.0 d=1.0
"""
where as it should be 
"""
f1 = @ode_def_nohes LotkaVolterraTest1 begin
  dx = a*x - b*x*y
  dy = -c*y + d*x*y
end a=>1.5 b=>1.0 c=>3.0 d=>1.0
"""
maybe that is why you are not able to recreate the error. The error in https://travis-ci.org/JuliaDiffEq/DiffEqBayes.jl/jobs/327872441#L1214 is exactly what I am getting locally too in case of 4 parameter version. 
@ChrisRackauckas the 4 parameter version does not work, I might have been doing something wrong if I said that, I have re-verified it.

**Comment by goedman** [comment]
Yes, you and Chris are correct. I did a Pkg.update() and now I see some errors (in normal_lpdf) and below result:

...

Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception: normal_lpdf: Scale parameter is -0.463446, but must be > 0!  (in '/Users/rob/.julia/v0.6/Stan/Examples/OtherExamples/DiffEqBayes/NewLotkaVolterra/tmp/parameter_estimation_model.stan' at line 34)

If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.


Calling /Users/rob/Projects/StanSupport/cmdstan/bin/stansummary to infer across chains.

Inference for Stan model: parameter_estimation_model_model
4 chains: each with iter=(1000,1000,1000,1000); warmup=(0,0,0,0); thin=(1,1,1,1); 4000 iterations saved.

Warmup took (34, 31, 37, 38) seconds, 2.3 minutes total
Sampling took (3.4, 2.7, 4.4, 1.9) seconds, 12 seconds total

                    Mean     MCSE   StdDev        5%       50%       95%  N_Eff  N_Eff/s    R_hat
lp__             1.4e+03  8.1e-01  1.8e+00   1.4e+03   1.4e+03   1.4e+03    5.0     0.40  1.4e+00
accept_stat__    7.1e-01  6.3e-02  2.7e-01   0.0e+00   8.0e-01   9.5e-01     18      1.5  1.1e+00
stepsize__       4.6e-02  4.2e-02  5.9e-02   1.3e-03   2.1e-02   1.5e-01    2.0     0.16  6.2e+14
treedepth__      2.0e+00  4.2e-01  1.2e+00   0.0e+00   2.0e+00   4.0e+00    7.8     0.63  1.1e+00
n_leapfrog__     7.4e+00  2.8e+00  6.8e+00   1.0e+00   5.0e+00   2.2e+01    5.9     0.48  1.2e+00
divergent__      1.0e+00  1.0e-03  6.5e-02   1.0e+00   1.0e+00   1.0e+00   4000      324  1.0e+00
energy__        -1.4e+03  8.3e-01  2.4e+00  -1.4e+03  -1.4e+03  -1.4e+03    8.2     0.67  1.2e+00
sigma[1]        7.0e+307      inf      inf  6.7e+306  6.3e+307  1.6e+308   4000      324      nan
sigma[2]        6.0e+307      inf      inf  4.3e+306  5.0e+307  1.6e+308   4000      324      nan
theta[1]         1.5e+00  1.8e-03  3.4e-03   1.5e+00   1.5e+00   1.5e+00    3.5     0.28  1.8e+00
params[1]        1.3e+01  1.1e+01  1.6e+01  -1.2e+01   2.6e+01   3.0e+01    2.0     0.16  5.9e+01
params[2]        1.4e-01  1.1e-02  1.9e-02   1.1e-01   1.5e-01   1.6e-01    3.0     0.24  1.8e+00

Samples were drawn using hmc with nuts.
For each parameter, N_Eff is a crude measure of effective sample size,
and R_hat is the potential scale reduction factor on split chains (at 
convergence, R_hat=1).

Testing a bit more.

**Comment by ChrisRackauckas** [comment]
My Linux machine is finally free so I can start digging into it a little bit more as well but probably not until later today

**Comment by goedman** [comment]
In Stan.jl (OtherExamples/DiffEqBayes/LotkaVolterra) the single and four params models seem to run. I would like to understand what happened/is happening to sigma, maybe a leftover? Plots don't look great.

**Comment by goedman** [comment]
Finally got the example set up correctly and indeed see the same failure messages and error code for the 4 parameter case. The next question is if defining a range for the mapping of internal_var___u[t] given the warnings in the run file (see also http://discourse.mc-stan.org/t/estimating-the-parameters-of-the-differential-equations-using-stan/1663/8 ), e.g.

Rejecting initial value:
  Error evaluating the log probability at the initial value.
Exception: normal_lpdf: Scale parameter is -1.00066, but must be > 0!  (in '/Users/rob/.julia/v0.6/Stan/Examples/OtherExamples/DiffEqBayes/LotkaVolterra1/tmp/parameter_estimation_model.stan' at line 33)

would solve this issue.

**Comment by ChrisRackauckas** [comment]
>The next question is if defining a range for the mapping of internal_var___u[t] given the warnings in the run file

What exactly does that warning mean? Log pdf of what variables?

Do you mean that we should truncate the ODE solution to handle its divergence? In the optimization problems we are able to give divergence solutions an infinite cost and that works well. 

One thing I just noticed:

```julia
theta[4] ~ normal(1.0, 1.0) T[0.0,1.0]
```

The truncations always seem to be `[0,1.0]` which doesn't center on the true solution well.

**Comment by ChrisRackauckas** [comment]
Here's a more up to date version of what's generated:

```julia
  functions {
    real[] sho(real t,real[] internal_var___u,real[] theta,real[] x_r,int[] x_i) {
      real internal_var___du[2];
       # /home/crackauc/Documents/test.jl, line 89:;
internal_var___du[1] = theta[1] * internal_var___u[1] - theta[2] * internal_var___u[1] * internal_var___u[2];
 # /home/crackauc/Documents/test.jl, line 90:;
internal_var___du[2] = -theta[3] * internal_var___u[2] + theta[4] * internal_var___u[1] * internal_var___u[2];

      return internal_var___du;
      }
    }
  data {
    real u0[2];
    int<lower=1> T;
    real internal_var___u[T,2];
    real t0;
    real ts[T];
  }
  transformed data {
    real x_r[0];
    int x_i[0];
  }
  parameters {
    vector<lower=0>[2] sigma;
    real theta[4];
    real params[2];
  }
  model{
    real u_hat[T,2];
    params[2] ~ inv_gamma(2.0, 3.0);
    theta[1] ~normal(1.5, 1.0) T[0.0,2.0];theta[2] ~normal(1.0, 1.0) T[0.0,2.0];theta[3] ~normal(3.0, 1.0);theta[4] ~normal(1.0, 1.0) T[0.0,2.0];;
    u_hat = integrate_ode_rk45(sho, u0, t0, ts, theta, x_r, x_i, 0.001, 1.0e-6, 100000);
    for (t in 1:T){
      internal_var___u[t] ~ normal(u_hat[t],params[2]);
      }
  }
```

so the truncations were fixed.

**Comment by ChrisRackauckas** [comment]
```julia
Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception: Max number of iterations exceeded (100000).  (in '/home/crackauc/.julia/tmp/parameter_estimation_model.stan' at line 32)

If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
```

Yeah, that's to be expected which is the divergence thing mentioned above.

I see where you're reading the logs and stuff now, I'll try to see what I come up with.

**Comment by ChrisRackauckas** [comment]
Where can we find information on what Stan error codes mean? `error code: -5` doesn't appear to be in the Stan documentation?

**Comment by ChrisRackauckas** [comment]
I think I fixed the likelihood statement. I was always failing for more than 2 parameters because of the vectorization being incorrect here.

```julia
functions {
    real[] sho(real t,real[] internal_var___u,real[] theta,real[] x_r,int[] x_i) {
      real internal_var___du[2];
       # /home/crackauc/.julia/v0.6/DiffEqBayes/test/stan.jl, line 25:;
internal_var___du[1] = theta[1] * internal_var___u[1] - theta[2] * internal_var___u[1] * internal_var___u[2];
 # /home/crackauc/.julia/v0.6/DiffEqBayes/test/stan.jl, line 26:;
internal_var___du[2] = -theta[3] * internal_var___u[2] + theta[4] * internal_var___u[1] * internal_var___u[2];

      return internal_var___du;
      }
    }
  data {
    real u0[2];
    int<lower=1> T;
    real internal_var___u[T,2];
    real t0;
    real ts[T];
  }
  transformed data {
    real x_r[0];
    int x_i[0];
  }
  parameters {
    row_vector<lower=0>[2] sigma1;
    real theta[4];
  }
  model{
    real u_hat[T,2];
    sigma1 ~ inv_gamma(4.0, 1.0);
    theta[1] ~normal(1.5, 0.01);theta[2] ~normal(1.0, 0.01);theta[3] ~normal(3.0, 0.01);theta[4] ~normal(1.0, 0.01);;
    u_hat = integrate_ode_rk45(sho, u0, t0, ts, theta, x_r, x_i, 0.001, 1.0e-6, 100000);
    for (t in 1:T){
      internal_var___u[t,:] ~ normal(u_hat[t,:],sigma1);
      }
  }
```

is what we have now.

Is there a way to set the initial parameters? Since it seems to make really bad choices quite often. @tpapp noted that he used optimization first to do it which seems reasonable.

**Comment by goedman** [comment]
Chris,

I've gone back to the single parameter case for now. I should mention though, I have never used truncated distributions and in any case, folks like Tamas know much, much more about all this!

Anyway, as I have mentioned several times I don't trust the plots that I see and e.g. below result I get for the single parameter case:

```
Warmup took (75, 68, 78, 78) seconds, 5.0 minutes total
Sampling took (100, 101, 107, 102) seconds, 6.8 minutes total

                    Mean     MCSE   StdDev        5%       50%       95%  N_Eff  N_Eff/s    R_hat
lp__             2.3e+01  5.2e-02  1.2e+00   2.1e+01   2.3e+01   2.4e+01    529  1.3e+00  1.0e+00
accept_stat__    9.2e-01  2.5e-03  1.1e-01   7.0e-01   9.6e-01   1.0e+00   1824  4.5e+00  1.0e+00
stepsize__       4.0e-01  1.5e-02  2.2e-02   3.6e-01   4.0e-01   4.2e-01    2.0  4.9e-03  8.0e+13
treedepth__      5.9e+00  8.1e-02  3.5e+00   2.0e+00   4.0e+00   1.0e+01   1888  4.6e+00  1.0e+00
n_leapfrog__     4.2e+02  1.1e+01  4.8e+02   3.0e+00   2.7e+01   1.0e+03   1867  4.6e+00  1.0e+00
divergent__      0.0e+00  0.0e+00  0.0e+00   0.0e+00   0.0e+00   0.0e+00   2000  4.9e+00      nan
energy__        -2.2e+01  6.7e-02  1.7e+00  -2.4e+01  -2.2e+01  -1.8e+01    663  1.6e+00  1.0e+00
theta[1]         1.5e+00  7.2e-05  3.2e-03   1.5e+00   1.5e+00   1.5e+00   2000  4.9e+00  1.0e+00
params[1]        2.1e+11  2.1e+11  5.1e+11  -9.7e+10  -3.3e+09   1.6e+12    6.2  1.5e-02  2.3e+00
params[2]        1.5e-01  1.4e-03  3.7e-02   1.1e-01   1.5e-01   2.2e-01    644  1.6e+00  1.0e+00
```

The values for params[1] are just plain wrong, which mean the internal_var__u[t] sampling in the model section is suspicious at least.

I added below update:

```
  parameters {
    real theta[$length_of_parameter];
    real<lower=0.1, upper=3.0> params[$length_of_params];
  }
```

Then I see a much better result (and plots in Stan.jl):

```
Warmup took (10, 23, 20, 22) seconds, 1.3 minutes total
Sampling took (31, 1.6, 2.2, 1.8) seconds, 37 seconds total

                Mean     MCSE   StdDev        5%   50%   95%  N_Eff  N_Eff/s    R_hat
lp__              19  1.1e-01  1.7e+00   1.5e+01    19    21    269      7.3  1.0e+00
accept_stat__   0.92  2.4e-03  1.1e-01   6.9e-01  0.96   1.0   2000       55  1.0e+00
stepsize__      0.35  1.4e-01  2.0e-01   6.2e-03  0.46  0.47    2.0    0.055  7.7e+14
treedepth__      3.5  1.1e+00  1.9e+00   2.0e+00   3.0   8.0    2.8    0.076  1.8e+00
n_leapfrog__      48  5.3e+01  9.7e+01   3.0e+00   7.0   255    3.3    0.091  1.5e+00
divergent__     0.00  0.0e+00  0.0e+00   0.0e+00  0.00  0.00   2000       55      nan
energy__         -17  1.2e-01  2.2e+00  -2.0e+01   -18   -13    307      8.4  1.0e+00
theta[1]         1.5  7.5e-05  3.4e-03   1.5e+00   1.5   1.5   2000       55  1.0e+00
params[1]        1.6  3.0e-02  8.5e-01   2.2e-01   1.6   2.9    809       22  1.0e+00
params[2]       0.15  1.3e-03  3.5e-02   1.1e-01  0.15  0.21    709       19  1.0e+00
```

[LotkaVolterra1-1.pdf](https://github.com/JuliaDiffEq/DiffEqBayes.jl/files/1629235/LotkaVolterra1-1.pdf)

I'm trying that now for the 4 parameter case to see if that helps there as well.

But the original suggestion on mc-stan's discourse ( http://discourse.mc-stan.org/t/estimating-the-parameters-of-the-differential-equations-using-stan/1663/8  "instead of constraints use a better prior distribution") is likely the way to go. But most likely beyond my skills/time constraints.

**Comment by ChrisRackauckas** [comment]
No variable `params` exists on master. It was changed to `sigma1` and is now part of what's passed in. However, `InverseGamma(4,1)` is what I was using in my tests above (with the 4 parameter case) and that's a naturally non-negative distribution with finite variance (whereas our previous one, `InverseGamma(2,3)`, was non-negative with infinite variance). I would assume the bounds wouldn't be as needed in that case?

**Comment by tpapp** [comment]
Just to clarify: constrained bounds and constrained priors are two different things.

When you use constraints `lower=0` or similar in Stan, it implicitly transforms from the real numbers to the right interval (or general domain). The implicit transformation here is `exp`. This means that the posterior is never evaluated with eg negative values. This is the right thing to do when feasible (ie the domai is easy to describe with such constraints).

If you simply set a prior with bounded support, the log posterior may still be evaluated outside it, it will just return `-Inf`. This is inefficient, and even though NUTS can cope with this for simple problems, it can easily throw off adaptation. So you should have **both** the constraint and an informative prior.

(Side note: these days people use the half-Cauchy prior of Polson and Scott (2012), it is cited in the Stan manual, really simple to do).

Finally, for the starting point: for well-behaved posteriors, it does not matter much. But for posteriors with multiple modes and near-0 outside a few "pinheads", it seems to. I think that unless told otherwise, Stan will start from a random vector in some interval, maybe `[-2,2]`, in the *untransformed* domain, then transfom this. Most of the time it works out. But ODEs seem to be tricky.

**Comment by ChrisRackauckas** [comment]
>When you use constraints lower=0 or similar in Stan, it implicitly transforms from the real numbers to the right interval (or general domain). The implicit transformation here is exp. This means that the posterior is never evaluated with eg negative values. This is the right thing to do when feasible (ie the domai is easy to describe with such constraints).

Thanks. So it sounds like we need options to not only pass in priors but also domains. I assumed that it just wouldn't go to where the prior is zero.

**Comment by ChrisRackauckas** [comment]
In the case of `real theta[4];`, is there a way to set upper and lower separately for each value? Or should we just generate those as `theta1`, `theta2`, ... . Since we are automatically generating the string it doesn't really matter which form we use, but it makes sense for us to translate any truncated distribution to have appropriate bounds.

**Comment by tpapp** [comment]
AFAIK in Stan, you would need to use separate variables if you want to set different constraints, so `theta1`, `theta2`, etc is the way to go.

Don't worry about truncated distributions if 

1. the truncation bound is (weakly) wider than the support (and it should be, as I explained above), and
2. it is otherwise independent of the problem parameters.

When this holds, the posterior will never be evaluated outside the domain, so whether the distribution is truncated is irrelevant.

**Comment by ChrisRackauckas** [comment]
Huh, that's really weird. I would've thought Stan would try to never step where there's zero probability. Well, that conceptual inaccuracy is what's causing the bug for sure. We'll get that fixed. Thanks @tpapp !

**Comment by tpapp** [comment]
It never *steps* there (the proposal is rejected), but it may try. Hence the inefficiency. My understanding is that the *sampler* per se will behave correctly (it has heuristics to handle this), but the adaptation suffers if there is mass around the edges.

**Comment by ChrisRackauckas** [comment]
@tpapp, @Vaibhavdixit02 's latest PR generates this:

```
functions {
    real[] sho(real t,real[] internal_var___u,real[] theta,real[] x_r,int[] x_i) {
      real internal_var___du[2];
       # /home/vaibhav/.julia/v0.6/DiffEqBayes/test/stan.jl, line 25:;
internal_var___du[1] = theta[1] * internal_var___u[1] - theta[2] * internal_var___u[1] * internal_var___u[2];
 # /home/vaibhav/.julia/v0.6/DiffEqBayes/test/stan.jl, line 26:;
internal_var___du[2] = -theta[3] * internal_var___u[2] + theta[4] * internal_var___u[1] * internal_var___u[2];

      return internal_var___du;
      }
    }
  data {
    real u0[2];
    int<lower=1> T;
    real internal_var___u[T,2];
    real t0;
    real ts[T];
  }
  transformed data {
    real x_r[0];
    int x_i[0];
  }
  parameters {
    row_vector<lower=0>[2] sigma1;
    real<lower=0.0,upper=2.0> theta1;real<lower=0.0,upper=1.5> theta2;real<lower=0.0,upper=4.0> theta3;real<lower=0.0,upper=2.0> theta4;
  }
  transformed parameters{
    real theta[4];
    theta[1] <- theta1;theta[2] <- theta2;theta[3] <- theta3;theta[4] <- theta4;
  }
  model{
    real u_hat[T,2];
    sigma1 ~ inv_gamma(4.0, 1.0);
    theta[1] ~normal(1.5, 0.01) T[0.0,2.0];theta[2] ~normal(1.0, 0.01) T[0.0,1.5];theta[3] ~normal(3.0, 0.01) T[0.0,4.0];theta[4] ~normal(1.0, 0.01) T[0.0,2.0];
    u_hat = integrate_ode_rk45(sho, u0, t0, ts, theta, x_r, x_i, 0.001, 1.0e-6, 100000);
    for (t in 1:T){
      internal_var___u[t,:] ~ normal(u_hat[t,:],sigma1);
      }
  }
```

and it's much more robust. Thank you for the bounds suggestion. Do you see anything else you'd change (or @goedman ?). Do you think keeping the theta vector to pass for the DiffEq is a good idea? If so, I think we can call this closed and Stan is pretty much set as a benchmark case!

**Comment by tpapp** [comment]
LGTM. As I said, you won't need the truncation bounds for the prior on the `theta`, they just have no effect.

Regarding the `theta` vector: only keep it if it simplifies the syntax for `sho`. Makes little difference to Stan either way, copying is cheap. If you can generate an `sho` source with the `theta1` etc directly, that could also work fine and simplify code. As always, benchmark, surprises can happen.

It will be great to have baseline benchmark.

**Comment by ChrisRackauckas** [comment]
Got it, thanks! We'll close this now since it seems about done.

**Comment by ChrisRackauckas** [comment]
I just checked the manual. The ODE solver has to use a vector of parameters so I guess we're good then. Cool.
